
use colombia;
select * from Doctors;
select * from Patients;

-- 15.Identify the top 5 doctors who generated the highest total 
-- revenue while serving the fewest unique patients (i.e., highest revenue efficiency).
select 
d.`Doctor ID`,d.`Doctor Name`,sum(d.`Total Bill`) 
as total_revenue,
count(distinct p.patient_id) as total_patient  
from Doctors d join Patients p 
on d.patient_id=p.patient_id
group by d.`Doctor ID`,d.`Doctor Name`
order by total_revenue desc,total_patient asc limit 5;

-- 16. Find the department where the average waiting 
-- time has decreased over three consecutive months. (SQL)
-- per department per month average waiting time
-- ranking
-- compare
with cte as (select department_referral,DATE_FORMAT(STR_TO_DATE(date,'%d-%m-%Y'),'%Y-%m') as month,avg(patient_waittime) as avg_wait
from Patients
group by department_referral,DATE_FORMAT(STR_TO_DATE(date,'%d-%m-%Y'),'%Y-%m')),

cte_1 as (select department_referral,month,avg_wait,lag(month) over(partition by department_referral order by month) as previous_month,
lag(avg_wait) over(partition by department_referral order by month) as previous_month_wait,
lead(month) over(partition by department_referral order by month) as next_month,
lead(avg_wait) over(partition by department_referral order by month) as next_month_wait
from cte)
select distinct department_referral from cte_1
where (previous_month is not null and previous_month_wait is not null and next_month is not null and next_month_wait is not null
	and previous_month_wait>avg_wait and avg_wait>next_month_wait);
    
-- 17.	Determine the ratio of male to female patients 
-- for each doctor and rank the doctors based on this ratio. (SQL)
with cte as (select d.`Doctor Name` as doctor_name,d.`Doctor ID` as doctor_id,(sum(case when p.patient_gender="M" then 1 else 0 end)/
sum(case when p.patient_gender="F" then 1 else 0 end)) as ratio
from Doctors d join Patients p on d.patient_id=p.patient_id
group by d.`Doctor Name`,d.`Doctor ID`)
select doctor_name,doctor_id,ratio,rank() over(order by ratio) as 'rank' from cte;

-- 18.	Calculate the average satisfaction score of 
-- patients for each doctor based on their visits. (SQL)
select d.`Doctor Name` as doctor_name,d.`Doctor ID`,round(avg(p.patient_sat_score),2) as avg_sat_score
from Doctors d join Patients p on d.patient_id=p.patient_id
group by d.`Doctor Name`,d.`Doctor ID`;

-- 19. Find doctors who have treated patients from different 
-- races and calculate the diversity of their patient base. (SQL)
select d.`Doctor Name` as doctor_name,d.`Doctor ID`,count(distinct p.patient_race) as diversity,count(*) as total_patients_treated
from Doctors d join Patients p on d.patient_id=p.patient_id
group by d.`Doctor Name`,d.`Doctor ID`;


-- 20.	Calculate the ratio of total bills generated by 
-- male patients to female patients for each department. (SQL)
select sum(case when p.patient_gender="F" then d.`Total Bill`  else 0 end)/
sum(case when p.patient_gender="M" then d.`Total Bill` else 0 end) as ratio
from Doctors d join Patients p on d.patient_id=p.patient_id;

-- 21.	Update the patient satisfaction score for all patients 
-- who visited the "General Practice" department and had a waiting time
--  of more than 30 minutes. Increase their satisfaction score by 2 points, 
--  but ensure that the satisfaction score does not exceed 10. (SQL)
SET SQL_SAFE_UPDATES = 0;
update Patients
set patient_sat_score=patient_sat_score+2
where patient_waittime>30 and department_referral="General Practice" and patient_sat_score<=8;








